#################
# Diagnostic Test
#################
## This is a standalone script, not part of the analysis.
## It's here to troubleshoot machine learning models in the analysis work.
## Ie. is the environment correctly functioning, what's wrong with the data set?
##################

#Suppress warnings generated by future deprecated libraries etc.
import warnings
warnings.filterwarnings('ignore')

#Load modified deepphos code
from deepphos import predict

#Example predictions using tidied data from the analysis.
predict.predict_for_deepphos('./data/processed/all_potential_ST.csv', "ST")
predict.predict_for_deepphos('./data/processed/all_potential_Y.csv', "Y")

#Look at readme.md if you are getting error codes.
